In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('final salary.csv')

In [3]:
dataset

Age  Gender Education Level                      Job Title  \
0     32    Male      Bachelor's              Software Engineer   
1     28  Female        Master's                   Data Analyst   
2     45    Male             PhD                 Senior Manager   
3     36  Female      Bachelor's                Sales Associate   
4     52    Male        Master's                       Director   
..   ...     ...             ...                            ...   
368   35  Female      Bachelor's       Senior Marketing Analyst   
369   43    Male        Master's         Director of Operations   
370   29  Female      Bachelor's         Junior Project Manager   
371   34    Male      Bachelor's  Senior Operations Coordinator   
372   44  Female             PhD        Senior Business Analyst   

     Years of Experience  Salary  
0                    5.0   90000  
1                    3.0   65000  
2                   15.0  150000  
3                    7.0   60000  
4                   20.0  200000  
..                   ...     ...  
368                  8.0   85000  
369                 19.0  170000  
370                  2.0   40000  
371                  7.0   90000  
372                 15.0  150000  

[373 rows x 6 columns]

In [4]:

num_unique_job_titles = dataset['Job Title'].nunique()
print(num_unique_job_titles)


174


In [5]:

insert_at = len(dataset.columns) - 1
dataset.insert(insert_at, 'JobTitle_freq_enc', dataset['Job Title'].map(dataset['Job Title'].value_counts()))
dataset = dataset.drop(columns=['Job Title'])

In [6]:
dataset

Age  Gender Education Level  Years of Experience  JobTitle_freq_enc  \
0     32    Male      Bachelor's                  5.0                  1   
1     28  Female        Master's                  3.0                  2   
2     45    Male             PhD                 15.0                  2   
3     36  Female      Bachelor's                  7.0                  2   
4     52    Male        Master's                 20.0                  1   
..   ...     ...             ...                  ...                ...   
368   35  Female      Bachelor's                  8.0                  9   
369   43    Male        Master's                 19.0                 11   
370   29  Female      Bachelor's                  2.0                  5   
371   34    Male      Bachelor's                  7.0                  4   
372   44  Female             PhD                 15.0                 10   

     Salary  
0     90000  
1     65000  
2    150000  
3     60000  
4    200000  
..      ...  
368   85000  
369  170000  
370   40000  
371   90000  
372  150000  

[373 rows x 6 columns]

In [7]:
X = dataset.iloc[: , :-1,].values

In [8]:
y = dataset.iloc[: , -1].values

In [9]:
print(X)

[[32 'Male' "Bachelor's" 5.0 1]
 [28 'Female' "Master's" 3.0 2]
 [45 'Male' 'PhD' 15.0 2]
 ...
 [29 'Female' "Bachelor's" 2.0 5]
 [34 'Male' "Bachelor's" 7.0 4]
 [44 'Female' 'PhD' 15.0 10]]


In [10]:
print(y)

[ 90000  65000 150000  60000 200000  55000 120000  80000  45000 110000
  75000 140000  65000 130000  40000 125000  90000 115000  35000 180000
  80000 190000  50000  60000 140000  45000 110000  40000 140000  90000
 250000  55000  75000  65000 170000  45000  60000 115000  40000 160000
  80000 190000  60000  45000 130000  40000  75000 180000 120000  35000
 130000  85000  60000 200000  50000  95000  65000 140000  55000 105000
 170000  50000  80000 180000  35000  90000 120000  45000  90000 150000
  65000  70000 190000  40000 120000  95000 160000 100000 180000  55000
  70000  80000  30000 250000  40000  95000  45000  80000 135000  55000
 120000  40000 105000 170000  75000  65000 160000  35000  90000 110000
  45000  95000 150000  50000  80000 220000  50000  60000 100000  40000
 110000  95000 130000  90000  35000  95000  65000 170000  45000 120000
 100000 180000  50000  80000 140000  40000  95000 110000  50000 105000
 160000  45000 100000 160000  35000  55000 140000  50000  60000 120000
  4000

In [11]:

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[: , 1] = le.fit_transform(X[: , 1])

In [12]:
print(X)

[[32 1 "Bachelor's" 5.0 1]
 [28 0 "Master's" 3.0 2]
 [45 1 'PhD' 15.0 2]
 ...
 [29 0 "Bachelor's" 2.0 5]
 [34 1 "Bachelor's" 7.0 4]
 [44 0 'PhD' 15.0 10]]


In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[: , 2] = le.fit_transform(X[: , 2])

In [14]:
print(X)

[[32 1 0 5.0 1]
 [28 0 1 3.0 2]
 [45 1 2 15.0 2]
 ...
 [29 0 0 2.0 5]
 [34 1 0 7.0 4]
 [44 0 2 15.0 10]]


In [16]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state= 0)

Random forest regression implementation

In [17]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=100,random_state=0)
regressor.fit(X_train, y_train)

RandomForestRegressor(random_state=0)

In [18]:
y_pred = regressor.predict(X_test)

In [19]:
print(y_pred)

[ 40050.          44126.75        44347.38095238 155300.
  85000.         161150.          54725.         130481.66666667
  40000.         174900.          55800.         127000.
 149350.          94300.         106050.          60250.
  52805.41666667  40000.         144000.         171466.66666667
  91300.         101000.         116975.          40000.
 173150.          41162.1         50375.          59277.5
 121113.33333333  60750.95238095  55850.          87700.
 110375.         133200.          54902.73809524 116750.
  64450.          97500.          95033.33333333  87700.
 120538.33333333 171685.         128100.         180018.33333333
 190666.66666667  39572.35        78508.33333333 119000.
  51033.33333333  93500.         109641.66666667  98472.02380952
  67200.          92300.          72687.5        171300.
  97950.          40000.          41020.          48165.75396825
  44347.38095238 132800.         155000.          39826.75
  35207.5        100314.16666667 101000.     

In [20]:
from sklearn.metrics import r2_score
r2_score_model = r2_score(y_test,y_pred)

In [21]:
print("r2_ score of model: " , r2_score_model)

r2_ score of model:  0.9364065634735443


In [22]:
input_data = (30, 'Female', "Master's", 4.0, 'Data Analyst')


age, gender_txt, edu_txt, exp, job_txt = input_data

In [23]:
gender_le = LabelEncoder()
gender_le.fit(['Male', 'Female'])
gender_num = gender_le.transform([gender_txt])

In [24]:
edu_le = LabelEncoder()
edu_le.fit(["Bachelor's", "Master's", "PhD"])
edu_num = edu_le.transform([edu_txt])

In [25]:
job_counts = pd.read_csv('final salary.csv')['Job Title'].value_counts()
job_freq = job_counts.get(job_txt, 0)

In [26]:
X_single = [[
    float(age),            
    float(gender_num[0]), 
    float(edu_num[0]),    
    float(exp),          
    float(job_freq)       
]]

In [27]:
job_counts = pd.read_csv('final salary.csv')['Job Title'].value_counts()
job_freq = job_counts.get(job_txt, 0)

In [28]:
import pickle

In [29]:
filename = 'salary_predictor.sav'

In [30]:
pickle.dump(regressor,open(filename , 'wb'))

In [31]:
loaded_model = pickle.load(open('salary_predictor.sav' , 'rb'))

In [32]:
predicted_salary = loaded_model.predict(X_single)
print(f"Predicted Salary: ${predicted_salary[0]:.2f}")

Predicted Salary: $64100.00
